services:
  pelak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - pelak-data:/data
    environment:
      SESSION_SECRET: change-me-to-a-long-random-string
      BOOTSTRAP_ADMIN_USERNAME: admin
      BOOTSTRAP_ADMIN_PASSWORD: admin123
      BOOTSTRAP_ADMIN_EMAIL: admin@hokmran.com
      NEXT_PUBLIC_SITE_URL: https://hokmran.darkube.ir
    restart: unless-stopped

volumes:
  pelak-data:
