export const CACHE_TAGS = {
  siteConfig: "site-config",
  theme: "theme",
  articles: "articles",
  authors: "authors",
  members: "members",
  topics: "topics",
  contentGroups: "content-groups",
  videos: "videos",
  playlists: "playlists",
  messages: "messages",
  article: (slug: string) => `article:${slug}`,
  author: (slug: string) => `author:${slug}`,
  member: (slug: string) => `member:${slug}`,
  topic: (slug: string) => `topic:${slug}`,
  contentGroup: (slug: string) => `content-group:${slug}`,
  video: (slug: string) => `video:${slug}`,
  playlist: (slug: string) => `playlist:${slug}`,
  message: (id: number) => `message:${id}`,
} as const;
